; Auto-generated. Do not edit!


(cl:in-package learning_actionlib-msg)


;//! \htmlinclude GripperFeedback.msg.html

(cl:defclass <GripperFeedback> (roslisp-msg-protocol:ros-message)
  ((fed
    :reader fed
    :initarg :fed
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass GripperFeedback (<GripperFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GripperFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GripperFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name learning_actionlib-msg:<GripperFeedback> is deprecated: use learning_actionlib-msg:GripperFeedback instead.")))

(cl:ensure-generic-function 'fed-val :lambda-list '(m))
(cl:defmethod fed-val ((m <GripperFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader learning_actionlib-msg:fed-val is deprecated.  Use learning_actionlib-msg:fed instead.")
  (fed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GripperFeedback>) ostream)
  "Serializes a message object of type '<GripperFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'fed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    ))
   (cl:slot-value msg 'fed))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GripperFeedback>) istream)
  "Deserializes a message object of type '<GripperFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'fed) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'fed)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GripperFeedback>)))
  "Returns string type for a message object of type '<GripperFeedback>"
  "learning_actionlib/GripperFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GripperFeedback)))
  "Returns string type for a message object of type 'GripperFeedback"
  "learning_actionlib/GripperFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GripperFeedback>)))
  "Returns md5sum for a message object of type '<GripperFeedback>"
  "0c1850c274a0f8122caeecb285d2bee2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GripperFeedback)))
  "Returns md5sum for a message object of type 'GripperFeedback"
  "0c1850c274a0f8122caeecb285d2bee2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GripperFeedback>)))
  "Returns full string definition for message of type '<GripperFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int64[] fed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GripperFeedback)))
  "Returns full string definition for message of type 'GripperFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int64[] fed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GripperFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'fed) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GripperFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GripperFeedback
    (cl:cons ':fed (fed msg))
))
